config/routes.rb
Rails.application.routes.draw do

  match 'tagged' => 'principal#tagged', :as => 'tagged', via: [:get, :post]

  devise_for :users 
      as :user do
      get 'users/alterar' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'   
    end

  get 'municipios/index'

  resources :users

  resources :entidades do
    resources :fotos,    :controller => "fotos"
    resources :projetos, :controller => "projetos"
    resources :cursos,   :controller => "cursos"
    resources :textos,   :controller => "textos"
    resources :audios,   :controller => "audios"
    resources :videos,   :controller => "videos"
  end

  # devise_for :users

  get 'principal/index'

  root 'principal#index'
  get '/ufs/:sigla/municipios', :to => 'municipios#index'
  get '/entidades/lista/:tipo', :to => 'entidades#lista'
end

app/models/texto.rb
class Texto < ActiveRecord::Base
  belongs_to :entidade
  has_attached_file :arquivo,
                    :url  => "/textos/:id/:basename_:style.:extension",
                    :path => ":rails_root/public/textos/:id/:basename_:style.:extension"

  validates_attachment_content_type :arquivo, :content_type => /.*/  

  validates :titulo, :presence => true

  acts_as_taggable_on :tags
end

app/controllers/textos_controller.rb
class TextosController < ApplicationController
  before_action :set_texto, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :only => [:new, :edit, :create, :update, :destroy]

  # GET /textos
  # GET /textos.json
  def index
    @dados = Entidade.friendly.find(params[:entidade_id])
    @textos = Texto.where("entidade_id = ?", @dados.id)
  end

  # GET /textos/1
  # GET /textos/1.json
  def show
    @dados = Entidade.friendly.find(params[:entidade_id])
  end

  # GET /textos/new
  def new
    @texto = Texto.new
    @dados = Entidade.friendly.find(params[:entidade_id])
    return false if !owner_verify(@dados, entidade_textos_url)
  end

  # GET /textos/1/edit
  def edit
    @dados = Entidade.friendly.find(params[:entidade_id])
    return false if !owner_verify(@dados, entidade_textos_url)
 end

  # POST /textos
  # POST /textos.json
  def create
    @texto = Texto.new(texto_params)
    @dados = Entidade.friendly.find(params[:entidade_id])

    respond_to do |format|
      if @texto.save
        format.html { redirect_to entidade_textos_path, notice: 'Texto foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @texto }
      else
        format.html { render :new }
        format.json { render json: @texto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /textos/1
  # PATCH/PUT /textos/1.json
  def update
    respond_to do |format|
      if @texto.update(texto_params)
        format.html { redirect_to entidade_textos_path, notice: 'Texto foi editado com sucesso.' }
        format.json { render :show, status: :ok, location: @texto }
      else
        format.html { render :edit }
        format.json { render json: @texto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /textos/1
  # DELETE /textos/1.json
  def destroy
    @texto.destroy
    respond_to do |format|
      format.html { redirect_to entidade_textos_url, notice: 'Texto foi apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_texto
      @texto = Texto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def texto_params
      params.require(:texto).permit(:titulo, :entidade_id, :arquivo, :tag_list)
    end
end

app/helpers/textos_helper.rb
module TextosHelper
end

app/views/textos/_form.html.erb
<%= form_for [@dados, @texto], :html => { :multipart => true, :class => "form-horizontal texto" } do |f| %>

    <% if @texto.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@texto.errors.count, "error") %> impediu de gravar:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @texto.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :titulo, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :titulo, :class => 'form-control' %>
    </div>
    <%= error_span(@texto[:titulo]) %>
  </div>

  <div class="control-group">
    <%= f.label :arquivo, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :arquivo %>
    </div>
    <%= error_span(@texto[:arquivo]) %>
  </div>

  <div class="control-group">
    <%= f.label :tags, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :tag_list %> (Use Virgula como Separador, Exemplo: Terreiro, Quilombo, Cultura)
    </div>
  </div>

  <%= f.hidden_field :entidade_id, :value => @dados.id %>

  <% if user_signed_in? %>
    <br/>
    <% if (current_user.email == @dados.email || current_user.admin?) ||  params[:action] == 'new' %>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")), entidade_textos_path, :class => 'btn btn-default' %>
    <% end %>
  <% end %>
<% end %>

app/views/textos/edit.html.erb
<%- model_class = Texto -%>
<div class="page-header">
  <h3>Editar <%= @texto.titulo %></h3>
</div>
<%= render :partial => 'form' %>

app/views/textos/index.html.erb
<%- model_class = Texto -%>
<div class="page-header">
  <h3>Textos</h3>
  <%= link_to "Voltar", entidade_path(@dados) %>
</div>
<% if @textos.size > 0%>
<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Título</th>
      <th>Arquivo</th>
      <th>Tags</th>
      <% if user_signed_in? %>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @textos.each do |texto| %>
      <tr>
        <td><%= link_to texto.id, entidade_texto_path(@dados, texto) %></td>
        <td><%= link_to texto.titulo, entidade_texto_path(@dados, texto) %></td>
        <td><%= link_to "Download", texto.arquivo.url %></td>
        <td><% texto.tags.each do |tag| %><%= " " + tag.name %><% end %></td>
        <% if user_signed_in? %>
           <% if (current_user.email == texto.entidade.email || current_user.admin?) %>
             <td>
               <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_entidade_texto_path(@dados, texto), :class => 'btn btn-default btn-xs' %>
               <%= link_to t('.destroy', :default => t("helpers.links.destroy")), entidade_texto_path(@dados, texto), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem certeza?')) }, :class => 'btn btn-xs btn-danger' %>
             </td>
           <% else %>
             <td></td>
           <% end %>
         <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% if user_signed_in? %>
  <% if (current_user.email == @dados.email || current_user.admin?) %>
    <%= link_to t('.new', :default => t("helpers.links.new")), new_entidade_texto_path, :class => 'btn btn-primary' %>
  <% end %>
<% end %>

<% else %>
  <center>
  <h3>
    Nenhuma Arquivo de Texto Enviado
    <% if user_signed_in? %>
      <% if (current_user.email == @dados.email || current_user.admin?) %>
        <br/></br>
        <%= link_to "Clique Aqui para Enviar um Arquivo de Texto", new_entidade_texto_path %>
      <% end %>
    <% end %>
  </h3>
  </center>
<% end %>

app/views/textos/new.html.erb
<%- model_class = Texto -%>
<div class="page-header">
  <h3>Enviar Novo Arquivo de Texto</h3>
</div>
<%= render :partial => 'form' %>

app/views/textos/show.html.erb
<%- model_class = Texto -%>
<div class="page-header">
  <h3><%= @texto.titulo %></h3>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:titulo) %>:</strong></dt>
  <dd><%= @texto.titulo %></dd>
  <dt><strong>Texto:</strong></dt>
  <dd>
    <%= link_to "Download", @texto.arquivo.url %>
  </dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")), entidade_textos_path, :class => 'btn btn-default'  %>

<% if user_signed_in? %>
  <% if (current_user.email == @texto.entidade.email || current_user.admin?) %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_entidade_texto_path(@dados, @texto), :class => 'btn btn-default' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")), entidade_texto_path(@dados, @texto), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem certeza?')) }, :class => 'btn btn-danger' %>
  <% end %>
<% end %>