config/routes.rb
Rails.application.routes.draw do

  match 'tagged' => 'principal#tagged', :as => 'tagged', via: [:get, :post]

  devise_for :users 
      as :user do
      get 'users/alterar' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'   
    end

  get 'municipios/index'

  resources :users

  resources :entidades do
    resources :fotos,    :controller => "fotos"
    resources :projetos, :controller => "projetos"
    resources :cursos,   :controller => "cursos"
    resources :textos,   :controller => "textos"
    resources :audios,   :controller => "audios"
    resources :videos,   :controller => "videos"
  end

  # devise_for :users

  get 'principal/index'

  root 'principal#index'
  get '/ufs/:sigla/municipios', :to => 'municipios#index'
  get '/entidades/lista/:tipo', :to => 'entidades#lista'
end

app/models/entidade.rb
class Entidade < ActiveRecord::Base
  extend FriendlyId
  friendly_id :entidade, use: :slugged

  geocoded_by :localizacao 
  after_validation :geocode 

  def localizacao
     "#{self.endereco}, #{self.municipio}, #{self.uf}, Brasil"
  end

  has_many :fotos,    :dependent => :destroy
  has_many :audios,   :dependent => :destroy
  has_many :videos,   :dependent => :destroy
  has_many :textos,   :dependent => :destroy
  has_many :cursos,   :dependent => :destroy
  has_many :projetos, :dependent => :destroy

  validates :entidade, :presence => true, :length => { :minimum => 5 }

end

app/controllers/entidades_controller.rb
class EntidadesController < ApplicationController
  before_action :set_entidade, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :only => [:new, :edit, :create, :update, :destroy]

  # GET /entidades/lista/tipo
  # GET /entidades/lista/tipo.json
  def lista
    @entidades = Entidade.select("entidade, slug, latitude, longitude, telecentro, id").where("#{params[:tipo]} = true")

    respond_to do |format|
      format.json { render json: @entidades }
    end
  end

  # GET /entidades
  # GET /entidades.json
  def index
    @entidades = Entidade.all
  end

  # GET /entidades/1
  # GET /entidades/1.json
  def show
  end

  # GET /entidades/new
  def new
    @entidade = Entidade.new
  end

  # GET /entidades/1/edit
  def edit
    @entidade = Entidade.friendly.find(params[:id])

    return false if !owner_verify(@entidade, entidade_url)
  end

  # POST /entidades
  # POST /entidades.json
  def create
    @entidade = Entidade.new(entidade_params)

    respond_to do |format|
      if @entidade.save
        format.html { redirect_to @entidade, notice: 'Entidade foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @entidade }
      else
        format.html { render :new }
        format.json { render json: @entidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entidades/1
  # PATCH/PUT /entidades/1.json
  def update
    respond_to do |format|
      if @entidade.update(entidade_params)
        format.html { redirect_to @entidade, notice: 'Entidade foi editado com sucesso.' }
        format.json { render :show, status: :ok, location: @entidade }
      else
        format.html { render :edit }
        format.json { render json: @entidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entidades/1
  # DELETE /entidades/1.json
  def destroy
    @entidade.destroy
    respond_to do |format|
      format.html { redirect_to entidades_url, notice: 'Entidade foi apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entidade
      @entidade = Entidade.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entidade_params
      params.require(:entidade).permit(:entidade, :slug, :email, :responsavel, :municipio, :uf, :endereco, :telefone, :descricao, :descritor, :telecentro, :gesac, :ponto_cultura, :estudo_cultural, :quilombo, :quilombo_urbano, :capoeira, :terreiro, :nucleo_formacao, :grupo_mestre, :radio, :estudio, :roupa_acessorio, :evento, :latitude, :longitude)
    end
end

app/helpers/entidades_helper.rb
module EntidadesHelper
end

app/views/entidades/_form.html.erb
<%= form_for @entidade, :html => { :class => "form-horizontal entidade" } do |f| %>

    <% if @entidade.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@entidade.errors.count, "error") %> impediu de gravar:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @entidade.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label "Entidade", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :entidade, :autofocus => true, :class => 'form-control', :maxlength => '254' %>
    </div>
    <%= error_span(@entidade[:entidade]) %>
  </div>

  <div class="control-group">
    <%= f.label "E-Mail", :class => 'control-label' %>
    <div class="controls">
      <% if params[:action] == 'new' %>
        <%= f.text_field :email, :value => current_user.email, :class => 'form-control', :maxlength => '254', :disabled => true %>
      <% else %>
        <%= f.text_field :email, :class => 'form-control', :maxlength => '254', :disabled => true %>
      <% end %>

    </div>
    <%= error_span(@entidade[:email]) %>
  </div>

  <% if params[:action] == 'new' %>
    <%= f.hidden_field :email, :value => current_user.email %>
  <% end %>

  <div class="control-group">
    <%= f.label "Responsável", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :responsavel, :class => 'form-control', :maxlength => '254' %>
    </div>
    <%= error_span(@entidade[:responsavel]) %>
  </div>

  <div class="control-group">
    <strong>UF</strong>
    <div class="controls">
        <%= f.collection_select :uf, Uf.all, :sigla, :sigla, {:prompt => true}, :id => 'uf' %>
    </div>
    <%= error_span(@entidade[:uf]) %>
  </div>

<div class="control-group" id='select-municipio'>
  <%= f.label "Município", :class => 'control-label' %>
  <div class="controls">
    <% municipios = Municipio.from("municipios, ufs as estado").where("estado.sigla ILIKE ?", @entidade.uf).where("estado.id = municipios.estado_id") %>
    <%= f.collection_select :municipio, municipios, :nome, :nome, { :selected => @entidade.municipio.to_s }, :id => 'municipio' %>
  </div>
</div>

  <div class="control-group">
    <%= f.label "Endereço", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :endereco, :class => 'form-control', :maxlength => '254' %>
    </div>
    <%= error_span(@entidade[:endereco]) %>
  </div>

  <div class="control-group">
    <%= f.label "Telefone", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :telefone, :class => 'form-control' %>
    </div>
    <%= error_span(@entidade[:telefone]) %>
  </div>

  <div class="control-group">
    <%= f.label "Descritor GESAC", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :descritor, :class => 'form-control' %>
    </div>
    <%= error_span(@entidade[:descritor]) %>
  </div>

  <div class="control-group">
    <%= f.label "Possui Telecentro?", :class => 'control-label' %>
    <div class="controls">
      <%= f.select :telecentro, 'Não' => false, 'Sim' => true %>
    </div>
    <%= error_span(@entidade[:telecentro]) %>
  </div>

  <div class="control-group">
    <%= f.label "É GESAC?", :class => 'control-label' %>
    <div class="controls">
      <%= f.select :gesac, 'Não' => false, 'Sim' => true %>
    </div>
    <%= error_span(@entidade[:gesac]) %>
  </div>

  <div class="control-group">
    <%= f.label "É Ponto de Cultura?", :class => 'control-label' %>
    <div class="controls">
      <%= f.select :ponto_cultura, 'Não' => false, 'Sim' => true %>
    </div>
    <%= error_span(@entidade[:ponto_cultura]) %>
  </div>

  <div class="control-group">
    <%= f.label "Possui Estudos Culturais?", :class => 'control-label' %>
    <div class="controls">
      <%= f.select :estudo_cultural, 'Não' => false, 'Sim' => true %>
    </div>
    <%= error_span(@entidade[:estudo_cultural]) %>
  </div>

  <div class="control-group">
    <%= f.label "É Quilombo?", :class => 'control-label' %>
    <div class="controls">
      <%= f.select :quilombo, 'Não' => false, 'Sim' => true %>
    </div>
    <%= error_span(@entidade[:quilombo]) %>
  </div>

  <div class="control-group">
    <%= f.label "É Quilombo Urbano?", :class => 'control-label' %>
    <div class="controls">
      <%= f.select :quilombo_urbano, 'Não' => false, 'Sim' => true %>
    </div>
    <%= error_span(@entidade[:quilombo_urbano]) %>
  </div>

  <div class="control-group">
    <%= f.label "Possui Capoeira?", :class => 'control-label' %>
    <div class="controls">
      <%= f.select :capoeira, 'Não' => false, 'Sim' => true %>
    </div>
    <%= error_span(@entidade[:capoeira]) %>
  </div>

  <div class="control-group">
    <%= f.label "É Comunidade Tradicional de Matriz Africana?", :class => 'control-label' %>
    <div class="controls">
      <%= f.select :terreiro, 'Não' => false, 'Sim' => true %>
    </div>
    <%= error_span(@entidade[:terreiro]) %>
  </div>

  <div class="control-group">
    <%= f.label "Possui Núcleo de Formação?", :class => 'control-label' %>
    <div class="controls">
      <%= f.select :nucleo_formacao, 'Não' => false, 'Sim' => true %>
    </div>
    <%= error_span(@entidade[:nucleo_formacao]) %>
  </div>

  <div class="control-group">
    <%= f.label "Grupo de Mestre?", :class => 'control-label' %>
    <div class="controls">
      <%= f.select :grupo_mestre, 'Não' => false, 'Sim' => true %>
    </div>
    <%= error_span(@entidade[:grupo_mestre]) %>
  </div>

  <div class="control-group">
    <%= f.label "Possuí Rádio?", :class => 'control-label' %>
    <div class="controls">
      <%= f.select :radio, 'Não' => false, 'Sim' => true %>
    </div>
    <%= error_span(@entidade[:radio]) %>
  </div>

  <div class="control-group">
    <%= f.label "Possui Estúdio?", :class => 'control-label' %>
    <div class="controls">
      <%= f.select :estudio, 'Não' => false, 'Sim' => true %>
    </div>
    <%= error_span(@entidade[:estudio]) %>
  </div>

  <div class="control-group">
    <%= f.label "Possui Roupas e Acessórios?", :class => 'control-label' %>
    <div class="controls">
      <%= f.select :roupa_acessorio, 'Não' => false, 'Sim' => true %>
    </div>
    <%= error_span(@entidade[:roupa_acessorio]) %>
  </div>

  <div class="control-group">
    <%= f.label "Realiza Eventos?", :class => 'control-label' %>
    <div class="controls">
      <%= f.select :evento, 'Não' => false, 'Sim' => true %>
    </div>
    <%= error_span(@entidade[:evento]) %>
  </div>

  <div class="control-group">
    <%= f.label "Descrição", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :descricao,:class => 'form-control', :cols => 64, :rows => 6, :maxlength => '4096' %>
    </div>
    <%= error_span(@entidade[:descricao]) %>
  </div>

  <% if user_signed_in? %>
    <br/>
    <% if (current_user.email == @entidade.email || current_user.admin?) ||  params[:action] == 'new' %>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")), entidades_path, :class => 'btn btn-default' %>
    <% end %>
  <% end %>

<% end %>

app/views/entidades/edit.html.erb
<%- model_class = Entidade -%>
<div class="page-header">
  <h3>Editar <%= @entidade.entidade %></h3>
</div>
<%= render :partial => 'form' %>

app/views/entidades/index.html.erb
<%- model_class = Entidade -%>
<div class="page-header">
  <h3><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h3>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Entidade</th>
      <th>UF</th>
      <th>Projetos</th>
      <th>Fotos</th>
      <th>Áudios</th>
      <th>Vídeos</th>
      <th>Textos</th>
      <th>Cursos</th>
      <% if user_signed_in? %>
        <th> <%= t '.actions', :default => t("helpers.actions") %> </th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @entidades.each do |entidade| %>
      <tr>
        <td><%= link_to entidade.id, entidade_path(entidade) %></td>
        <td><%= link_to truncate(entidade.entidade, :length => 64, :omission => '...'), entidade_path(entidade) %></td>
        <td><%= entidade.uf %></td>
        <td><%= link_to entidade.projetos.size, entidade_projetos_path(entidade) %></td>
        <td><%= link_to entidade.fotos.size, entidade_fotos_path(entidade) %></td>
        <td><%= link_to entidade.audios.size, entidade_audios_path(entidade) %></td>
        <td><%= link_to entidade.videos.size, entidade_videos_path(entidade) %></td>
        <td><%= link_to entidade.textos.size, entidade_textos_path(entidade) %></td>
        <td><%= link_to entidade.cursos.size, entidade_cursos_path(entidade) %></td>
        <% if user_signed_in? %>
           <% if (current_user.email == entidade.email || current_user.admin?) %>
             <td>
               <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_entidade_path(entidade), :class => 'btn btn-default btn-xs' %>
               <%= link_to t('.destroy', :default => t("helpers.links.destroy")), entidade_path(entidade), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem certeza?')) }, :class => 'btn btn-xs btn-danger' %>
            </td>
          <% else %>
            <td></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")), new_entidade_path, :class => 'btn btn-primary' if user_signed_in? %>

app/views/entidades/new.html.erb
<%- model_class = Entidade -%>
<div class="page-header">
  <h3>Cadastrar Nova Entidade</h3>
</div>
<%= render :partial => 'form' %>

app/views/entidades/show.html.erb
<%- model_class = Entidade -%>
<div class="page-header">
  <h3><%=@entidade.entidade %></h3>
  <%= link_to "Projetos (#{@entidade.projetos.size.to_s})", entidade_projetos_path(@entidade) %> 
  <% if user_signed_in? %> <% if (current_user.email == @entidade.email || current_user.admin?) %> <strong style="font-size:9px;"> (<%= link_to "Enviar Novo", new_entidade_projeto_path(@entidade), :style => 'color: #FF2D2D;' %>) </strong> <% end %> <% end %> | 
  <%= link_to "Fotos  (#{@entidade.fotos.size.to_s})", entidade_fotos_path(@entidade) %>
  <% if user_signed_in? %> <% if (current_user.email == @entidade.email || current_user.admin?) %> <strong style="font-size:9px"> (<%= link_to "Enviar Novo", new_entidade_foto_path(@entidade), :style => 'color: #FF2D2D;' %>) </strong> <% end %> <% end %> | 
  <%= link_to "Áudios (#{@entidade.audios.size.to_s})", entidade_audios_path(@entidade) %>
  <% if user_signed_in? %> <% if (current_user.email == @entidade.email || current_user.admin?) %> <strong style="font-size:9px"> (<%= link_to "Enviar Novo", new_entidade_audio_path(@entidade), :style => 'color: #FF2D2D;' %>) </strong> <% end %> <% end %> | 
  <%= link_to "Videos (#{@entidade.videos.size.to_s})", entidade_videos_path(@entidade) %>
  <% if user_signed_in? %> <% if (current_user.email == @entidade.email || current_user.admin?) %> <strong style="font-size:9px"> (<%= link_to "Enviar Novo", new_entidade_video_path(@entidade), :style => 'color: #FF2D2D;' %>) </strong> <% end %> <% end %> | 
  <%= link_to "Textos (#{@entidade.textos.size.to_s})", entidade_textos_path(@entidade) %>
  <% if user_signed_in? %> <% if (current_user.email == @entidade.email || current_user.admin?) %> <strong style="font-size:9px"> (<%= link_to "Enviar Novo", new_entidade_texto_path(@entidade), :style => 'color: #FF2D2D;' %>) </strong> <% end %> <% end %> | 
  <%= link_to "Cursos (#{@entidade.cursos.size.to_s})", entidade_cursos_path(@entidade) %> 
  <% if user_signed_in? %> <% if (current_user.email == @entidade.email || current_user.admin?) %> <strong style="font-size:9px"> (<%= link_to "Enviar Novo", new_entidade_curso_path(@entidade), :style => 'color: #FF2D2D;' %>) </strong> <% end %> <% end %>
</div>

<dl class="dl-horizontal">
  <dt><strong>E-Mail:</strong></dt>
  <dd><%= @entidade.email %></dd>
  <dt><strong>Responsável:</strong></dt>
  <dd><%= @entidade.responsavel %></dd>
  <dt><strong>Município:</strong></dt>
  <dd><%= @entidade.municipio %></dd>
  <dt><strong>UF:</strong></dt>
  <dd><%= @entidade.uf %></dd>

  <% if user_signed_in? %>
    <% if (current_user.email == @entidade.email || current_user.admin?) %>
      <dt><strong>Endereço:</strong></dt>
      <dd><%= @entidade.endereco %></dd>
      <dt><strong>Telefone:</strong></dt>
      <dd><%= @entidade.telefone %></dd>
    <% end %>
  <% end %>

  <dt><strong>Descritor GESAC:</strong></dt>
  <dd><%= @entidade.descritor %></dd>
  <dt><strong>Possui Telecentro?:</strong></dt>
  <dd><%= I18n.t(@entidade.telecentro.to_s) %></dd>
  <dt><strong>É GESAC?:</strong></dt>
  <dd><%= I18n.t(@entidade.gesac.to_s) %></dd>
  <dt><strong>É Ponto de Cultura?:</strong></dt>
  <dd><%= I18n.t(@entidade.ponto_cultura.to_s) %></dd>
  <dt><strong>Possui Estudos Culturais?:</strong></dt>
  <dd><%= I18n.t(@entidade.estudo_cultural.to_s) %></dd>
  <dt><strong>É Quilombo?:</strong></dt>
  <dd><%= I18n.t(@entidade.quilombo.to_s) %></dd>
  <dt><strong>É Quilombo Urbano?:</strong></dt>
  <dd><%= I18n.t(@entidade.quilombo_urbano.to_s) %></dd>
  <dt><strong>Possui Capoeira?:</strong></dt>
  <dd><%= I18n.t(@entidade.capoeira.to_s) %></dd>
  <dt><strong>É Terreiro?:</strong></dt>
  <dd><%= I18n.t(@entidade.terreiro.to_s) %></dd>
  <dt><strong>Possui Núcleo de Formação?:</strong></dt>
  <dd><%= I18n.t(@entidade.nucleo_formacao.to_s) %></dd>
  <dt><strong>Possui Grupo de Mestres?:</strong></dt>
  <dd><%= I18n.t(@entidade.grupo_mestre.to_s) %></dd>
  <dt><strong>Possui Rádio?:</strong></dt>
  <dd><%= I18n.t(@entidade.radio.to_s) %></dd>
  <dt><strong>Possui Estúdo?:</strong></dt>
  <dd><%= I18n.t(@entidade.estudio.to_s) %></dd>
  <dt><strong>Possui Roupas e Acessórios?:</strong></dt>
  <dd><%= I18n.t(@entidade.roupa_acessorio.to_s) %></dd>
  <dt><strong>Realiza Eventos?:</strong></dt>
  <dd><%= I18n.t(@entidade.evento.to_s) %></dd>
  <dt><strong>Descrição:</strong></dt>
  <dd><%= @entidade.descricao %></dd>

  <br/>
  <dt><strong>Localização</strong></dt>
  <dd>
    <%= map(:center  => {:latlng => [@entidade.latitude, @entidade.longitude], :zoom => 8 },
            :markers => [ {:latlng => [@entidade.latitude, @entidade.longitude], :popup => "#{@entidade.entidade}"}] ) %>
  </dd>

</dl>

<%= link_to t('.back', :default => t("helpers.links.back")), entidades_path, :class => 'btn btn-default'  %>
<% if user_signed_in? %>
  <% if (current_user.email == @entidade.email || current_user.admin?) %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_entidade_path(@entidade), :class => 'btn btn-default' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")), entidade_path(@entidade), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem certeza?')) }, :class => 'btn btn-danger' %>
  <% end %>
<% end %>