config/routes.rb
Rails.application.routes.draw do

  match 'tagged' => 'principal#tagged', :as => 'tagged', via: [:get, :post]

  devise_for :users 
      as :user do
      get 'users/alterar' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'   
    end

  get 'municipios/index'

  resources :users

  resources :entidades do
    resources :fotos,    :controller => "fotos"
    resources :projetos, :controller => "projetos"
    resources :cursos,   :controller => "cursos"
    resources :textos,   :controller => "textos"
    resources :audios,   :controller => "audios"
    resources :videos,   :controller => "videos"
  end

  # devise_for :users

  get 'principal/index'

  root 'principal#index'
  get '/ufs/:sigla/municipios', :to => 'municipios#index'
  get '/entidades/lista/:tipo', :to => 'entidades#lista'
end

app/models/foto.rb
class Foto < ActiveRecord::Base
  belongs_to :entidade

  has_attached_file :imagem,
                    :url  => "/fotos/:id/:basename_:style.:extension",
                    :path => ":rails_root/public/fotos/:id/:basename_:style.:extension",
                    :styles => { :medium => "400x400>", :thumb => "150x150>" },
                    :default_url => "/images/:style/missing.png"

  validates_attachment_content_type :imagem, :content_type => /\Aimage\/.*\Z/

  validates :titulo, :presence => true

  acts_as_taggable_on :tags
end

app/controllers/fotos_controller.rb
class FotosController < ApplicationController
  before_action :set_foto, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :only => [:new, :edit, :create, :update, :destroy]

  # GET /fotos
  # GET /fotos.json
  def index
    @dados = Entidade.friendly.find(params[:entidade_id])
    @fotos = Foto.where("entidade_id = ?", @dados.id)
  end

  # GET /fotos/1
  # GET /fotos/1.json
  def show
    @dados = Entidade.friendly.find(params[:entidade_id])
  end

  # GET /fotos/new
  def new
    @foto = Foto.new
    @dados = Entidade.friendly.find(params[:entidade_id])
    return false if !owner_verify(@dados, entidade_fotos_url)
  end

  # GET /fotos/1/edit
  def edit
    @dados = Entidade.friendly.find(params[:entidade_id])
    return false if !owner_verify(@dados, entidade_fotos_url)
 end

  # POST /fotos
  # POST /fotos.json
  def create
    @foto = Foto.new(foto_params)
    @dados = Entidade.friendly.find(params[:entidade_id])

    respond_to do |format|
      if @foto.save
        format.html { redirect_to entidade_fotos_path, notice: 'Foto foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @foto }
      else
        format.html { render :new }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fotos/1
  # PATCH/PUT /fotos/1.json
  def update
    respond_to do |format|
      if @foto.update(foto_params)
        format.html { redirect_to entidade_fotos_path, notice: 'Foto foi editado com sucesso.' }
        format.json { render :show, status: :ok, location: @foto }
      else
        format.html { render :edit }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fotos/1
  # DELETE /fotos/1.json
  def destroy
    @foto.destroy
    respond_to do |format|
      format.html { redirect_to entidade_fotos_url, notice: 'Foto foi apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

  def tagged
    if params[:tag].present?
      @fotos = Foto.tagged_with(params[:tag])
    else
      @fotos = Foto.all
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foto
      @foto = Foto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foto_params
      params.require(:foto).permit(:titulo, :entidade_id, :imagem, :tag_list)
    end
end

app/helpers/fotos_helper.rb
module FotosHelper
end

app/views/fotos/_form.html.erb
<%= form_for [@dados, @foto], :html => { :multipart => true, :class => "form-horizontal foto" } do |f| %>

    <% if @foto.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@foto.errors.count, "error") %> impediu de gravar:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @foto.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :titulo, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :titulo, :class => 'form-control' %>
    </div>
    <%= error_span(@foto[:titulo]) %>
  </div>

  <div class="control-group">
    <%= f.label :imagem, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :imagem %>
    </div>
    <%= error_span(@foto[:imagem]) %>
  </div>

  <div class="control-group">
    <%= f.label :tags, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :tag_list %> (Use Virgula como Separador, Exemplo: Terreiro, Quilombo, Cultura)
    </div>
  </div>

  <%= f.hidden_field :entidade_id, :value => @dados.id %>

  <% if user_signed_in? %>
    <br/>
    <% if (current_user.email == @dados.email || current_user.admin?) ||  params[:action] == 'new' %>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")), entidade_fotos_path, :class => 'btn btn-default' %>
    <% end %>
  <% end %>
<% end %>

app/views/fotos/edit.html.erb
<%- model_class = Foto -%>
<div class="page-header">
  <h3>Editar <%= @foto.titulo %></h3>
</div>
<%= render :partial => 'form' %>

app/views/fotos/index.html.erb
<%- model_class = Foto -%>
<div class="page-header">
  <h3><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h3>
  <%= link_to "Voltar", entidade_path(@dados) %>
</div>
<% if @fotos.size > 0%>
<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Título</th>
      <th>Imagem</th>
      <% if user_signed_in? %>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @fotos.each do |foto| %>
      <tr>
        <td><%= link_to foto.id, entidade_foto_path(@dados, foto) %></td>
        <td><%= link_to foto.titulo, entidade_foto_path(@dados, foto) %></td>
        <td><%= link_to (image_tag foto.imagem.url(:thumb), :alt => foto.titulo, :title => foto.titulo), foto.imagem.url %></td>
        <% if user_signed_in? %>
           <% if (current_user.email == foto.entidade.email || current_user.admin?) %>
             <td>
               <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_entidade_foto_path(@dados, foto), :class => 'btn btn-default btn-xs' %>
               <%= link_to t('.destroy', :default => t("helpers.links.destroy")), entidade_foto_path(@dados, foto), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem certeza?')) }, :class => 'btn btn-xs btn-danger' %>
             </td>
           <% else %>
             <td></td>
           <% end %>
         <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% if user_signed_in? %>
  <% if (current_user.email == @dados.email || current_user.admin?) %>
    <%= link_to t('.new', :default => t("helpers.links.new")), new_entidade_foto_path, :class => 'btn btn-primary' %>
  <% end %>
<% end %>

<% else %>
  <center>
  <h3>
    Nenhuma Foto Enviada
    <% if user_signed_in? %>
      <% if (current_user.email == @dados.email || current_user.admin?) %>
        <br/></br>
        <%= link_to "Clique Aqui para Enviar uma Foto", new_entidade_foto_path %>
      <% end %>
    <% end %>
  </h3>
  </center>
<% end %>

app/views/fotos/new.html.erb
<%- model_class = Foto -%>
<div class="page-header">
  <h3>Enviar Nova Foto</h3>
</div>
<%= render :partial => 'form' %>

app/views/fotos/show.html.erb
<%- model_class = Foto -%>
<div class="page-header">
  <h3><%= @foto.titulo %></h3>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:titulo) %>:</strong></dt>
  <dd><%= @foto.titulo %></dd>
  <dt><strong>Foto:</strong></dt><br/>
  <dd>
    <%= link_to (image_tag @foto.imagem.url(:medium), :alt => @foto.titulo, :title => @foto.titulo), @foto.imagem.url %>
  </dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")), entidade_fotos_path, :class => 'btn btn-default'  %>

<% if user_signed_in? %>
  <% if (current_user.email == @foto.entidade.email || current_user.admin?) %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_entidade_foto_path(@dados, @foto), :class => 'btn btn-default' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")), entidade_foto_path(@dados, @foto), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem certeza?')) }, :class => 'btn btn-danger' %>
  <% end %>
<% end %>

app/views/fotos/tagged.html.erb
<h1><%= Fotos %></h1>

<div class="tab-content">
  <div class="active tab-pane" id="list">
    <%= render 'list', :fotos => @fotos %>
  </div>
</div>